export enum DatabaseColumns {
  UserId = 'userid',
  EventId = 'eventid',
  CollaboratorId = 'collaboratorid',
  IsActive = 'isactive',
  IsPublic = 'ispublic',
  EntityId = 'id',
  AuthorId = 'authorid',
  Email = 'email',
  Endpoint = 'endpoint',
  Keys = 'keys',
  ExpirationTime = 'expirationtime',
  DateCreated = 'datecreated',
  Password = 'password',
  All = '*',
  Name = 'name',
  Surname = 'surname',
  CreatedDate = 'createddate',
  Code = 'code',
}