export enum DatabaseColumns {
  UserId = 'userid',
  EventId = 'eventid',
  CollaboratorId = 'collaboratorid',
  IsActive = 'isactive',
  IsPublic = 'ispublic',
  EntityId = 'id',
  AuthorId = 'authorid',
  Email = 'email',
  Endpoint = 'endpoint',
  Keys = 'keys',
  ExpirationTime = 'expirationtime',
  DateCreated = 'datecreated',
  Password = 'password',
  All = '*',
  Name = 'name',
  Surname = 'surname',
  Code = 'code',
  TargetUserId = "targetuserid",
  Status = "status",
  RequestedDate = "requesteddate",
  RequesterUserId = "requesteruserid",
  RequesterCollaboratorId = "requestercollaboratorid",
  TargetCollaboratorEmail = "TargetCollaboratorEmail",
}