export enum TableEnum {
  Events = 'events',
  Users = 'users',
  WebPushToken = 'webpushtoken',
  EventFollows = 'eventfollows',
  Payments = 'payments',
  Savings = 'savings',
  Types = 'types',
  Periods = 'periods',
  Currencies = 'currencies',
  Collaborators = 'collaborators',
  Transactions = 'transactions',
  TransactionSplits = 'transactionsplits',
  Projects = 'projects',
  ProjectMembers = 'projectmembers',
  ProjectTransactions = 'projecttransactions',
  CollaboratorMatches = 'collaboratormatches',
  CollaboratorMatchRequests = 'collaboratormatchrequests',
  TransactionReimbursements = "transactionreimbursements",
}
