export enum TableEnum {
  Events = 'events',
  Users = 'users',
  WebPushToken = 'webpushtoken',
  EventFollows = 'eventfollows',
  Payments = 'payments',
  Savings = 'savings',
  Types = 'types',
  Periods = 'periods',
  Currencies = 'currencies',
  Collaborators = 'collaborators',
  Transactions = 'transactions',
  TransactionSplits = 'transactionsplits',
  CollaboratorMatches = 'collaboratormatches',
  CollaboratorMatchRequests = 'collaboratormatchrequests',
  TransactionReimbursements = "transactionreimbursements",
  PasswordResetTokens = 'passwordresettokens',
  EmailVerificationTokens = 'emailverificationtokens',
  SavingsGoals = 'savingsgoals',
  SavingsInstallments = 'savingsinstallments',
  SavingsDeposits = 'savingsdeposits',
  SavingsProgressionTypes = 'savingsprogressiontypes',
  SavingsStatus = 'savingsstatus',
  InstallmentStatus = 'installmentstatus',
  
  // ===== TRAVEL MODULE TABLES =====
  Travels = 'travels',
  TravelMembers = 'travelmembers',
  TravelOperations = 'traveloperations',
  TravelOperationParticipants = 'traveloperationparticipants',
  TravelOperationApprovals = 'traveloperationapprovals',
  PaymentMethods = 'paymentmethods',
}