export const AUTH_CONFIG = {
  PASSWORD_RESET: {
    TOKEN_LENGTH: 64,
    EXPIRY_HOURS: 2,
    MAX_ATTEMPTS_PER_HOUR: 3,
  },
  EMAIL_VERIFICATION: {
    TOKEN_LENGTH: 64,
    EXPIRY_DAYS: 7,
    MAX_RESEND_PER_HOUR: 3,
  },
  RATE_LIMIT: {
    RESET_PASSWORD_MAX_ATTEMPTS: 5,
  },
} as const;